#!/bin/bash

d="\e[33;1m" 
n="\e[36;1m" 




printf "\n ${d}"
	printf "

              ██     ██ ██████     ███████   ████     ████ ██████  
             ░░██   ██ ░█░░░░██   ██░░░░░██ ░██░██   ██░██░█░░░░██ 
              ░░██ ██  ░█   ░██  ██     ░░██░██░░██ ██ ░██░█   ░██ 
               ░░███   ░██████  ░██      ░██░██ ░░███  ░██░██████  
                ██░██  ░█░░░░ ██░██      ░██░██  ░░█   ░██░█░░░░ ██
               ██ ░░██ ░█    ░██░░██     ██ ░██   ░    ░██░█    ░██
              ██   ░░██░███████  ░░███████  ░██        ░██░███████ 
             ░░     ░░ ░░░░░░░    ░░░░░░░   ░░         ░░ ░░░░░░░  "

printf "\n ${n}"
	printf "
                      ┏━┓┏┓ ╺┳┓╻ ╻╻  ╻  ┏━┓╻ ╻ ┏┓╻┏━╸╺┳╸  
                      ┣━┫┣┻┓ ┃┃┃ ┃┃  ┃  ┣━┫┣━┫ ┃┗┫┣╸  ┃   
                      ╹ ╹┗━┛╺┻┛┗━┛┗━╸┗━╸╹ ╹╹ ╹╹╹ ╹┗━╸ ╹ 
"










for i in {1..10000}
do
  # Simulate pressing Ctrl + V to paste
  xdotool keydown ctrl key v keyup ctrl
  
  # Simulate pressing Enter
  xdotool key Return

  # Wait 1 second before the next iteration
  sleep 1
done
